// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getSupabaseUrl = () => {
  const url = import.meta.env.VITE_SUPABASE_URL;
  if (!url) {
    throw new Error(
      'VITE_SUPABASE_URL is not defined in the environment variables'
    );
  }

  // Handle case where user accidentally puts the dashboard URL
  if (url.includes('supabase.com/dashboard/project/')) {
    const match = url.match(/project\/([a-z0-9]+)/);
    if (match && match[1]) {
      return `https://${match[1]}.supabase.co`;
    }
  }
  return url;
};

const getSupabaseAnonKey = () => {
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (!key) {
    throw new Error(
      'VITE_SUPABASE_ANON_KEY is not defined in the environment variables'
    );
  }
  return key;
};

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = getSupabaseAnonKey();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false, // Faster init - no URL parsing
    },
    global: {
      headers: {
        'x-client-info': 'flo-app/1.0', // Helps with debugging
      },
    },
    // Optimize realtime connections
    realtime: {
      params: {
        eventsPerSecond: 10, // Rate limit realtime events
      },
    },
  }
);
